### ISSUE TITLE
DataParallel wrapper issue

### ISSUE THREAD

**Issue by bfrink** [Jungjee/ASVspoof2019_PA#7]
Hi,

I am having issues running "g1-train_model.py" and "g2-train_train_model_CNN_GRU_wPretrn.py" as they are throwing the errors seen below respectively. Do you have any suggestions on how to access your models methods when wrapped in DataParallel? Would replacing model.METHOD_NAME -> model.module.METHOD_NAME be appropriate?

torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'compute_center_loss'
torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'forward_mode'

Thanks in advance!

**Comment by Jungjee** [comment]
In my opinion, 
  1. moving center loss related functions into the model's "forward" function will allow per-GPU processing.
  2. Yes, or changing "forward_mode" before wrapping would be more recommended

This might be wrong since I didn't verify its validity. Please let me know if you get this solved:)

**Comment by bfrink** [comment]
Thank you for the quick reply,

For the CNN model, I decided to call the attributes that were causing the errors via model.module.ATTRIB_NAME, as I tried to move the center loss relation functions into the model's 'forward function' and that seemed to work, but when it got to the backward propagation stage it through an attribute error for the 'get_center_deltas'.

For the CNN-GRU model training I noticed you saved the model.module.state_dict, so I just had move the assert prior to wrapping the model and change the load statement to 'model.module.load_state_dict(torch.load(save_dir + 'models/best.pt'))'

**Comment by Jungjee** [comment]
Thank you 👍 

For the CNN model, I decided to call the attributes that were causing the errors via model.module.ATTRIB_NAME, as I tried to move the center loss relation functions into the model's 'forward function' and that seemed to work, but when it got to the backward propagation stage it through an attribute error for the 'get_center_deltas'.
>>> I don't know which attribute causes the error exactly, but I think it's possible to 'get_center_deltas' with DataParallel mechanism. 
However, since in DataParalle, you would be calculating centers per each GPU, I suggest either using DistributedDataParallel (it will require quite a lot of modification...) or removing the center and bs loss :)

For the CNN-GRU model training I noticed you saved the model.module.state_dict, so I just had move the assert prior to wrapping the model and change the load statement to 'model.module.load_state_dict(torch.load(save_dir + 'models/best.pt'))'
>>> Great!
